config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "home#index"
  resources :warehouses, only: [:show, :new, :create, :edit, :update, :destroy]
  resources :suppliers, only: [:index, :show, :new, :create, :edit, :update]
  resources :product_models, only: [:index, :new, :create, :show]
  resources :orders, only: [:new, :create, :show, :index, :edit, :update] do
    get "search", on: :collection
    post "delivered", on: :member
    post "canceled", on: :member
    resources :order_items, only: [:new, :create]
  end

  namespace :api do
    namespace :v1 do
      resources :warehouses, only: [:show, :index, :create]
    end
  end

end

app/models/product_model.rb
class ProductModel < ApplicationRecord
  belongs_to :supplier
  has_many :order_items
  has_many :orders, through: :order_items
  validates :name, :sku, presence: true
end

app/controllers/product_models_controller.rb
class ProductModelsController < ApplicationController
    before_action :authenticate_user!, only: [:index]

    def index
      @product_models = ProductModel.all
    end

    def new
      @product_model = ProductModel.new
      @suppliers = Supplier.all
    end

    def create
      @product_model = ProductModel.new(product_model_params)
      if @product_model.save
        return redirect_to @product_model, notice: "Product model successfully registered!"
      end
      flash.now[:notice] = "Unable to register product model"
      @suppliers = Supplier.all #very important!!!
      render "new"
    end

    def show
      @product_model = ProductModel.find(params[:id])
    end

    private
    def product_model_params
      params.require(:product_model).permit(
        :name,
        :weight,
        :height,
        :width,
        :depth,
        :sku,
        :supplier_id
      )
    end
end

app/views/product_models/_form.html.erb
<div>
  <%= form_with model: product_model do |f| %>
    <div>
      <%= f.label :name %>
      <%= f.text_field :name %>
    </div>
    <div>
      <%= f.label :weight %>
      <%= f.number_field :weight %>
    </div>
    <div>
      <%= f.label :width %>
      <%= f.number_field :width %>
    </div>
    <div>
      <%= f.label :height %>
      <%= f.number_field :height %>
    </div>
    <div>
      <%= f.label :depth %>
      <%= f.number_field :depth %>
    </div>
    <div>
      <%= f.label :sku %>
      <%= f.text_field :sku %>
    </div>
    <div>
      <%= f.label :supplier_id, "Supplier" %>
      <%= f.collection_select :supplier_id, suppliers, :id, :brand_name %>
    </div>
    <%= f.submit "Save" %>
  <% end %>
</div>

app/views/product_models/index.html.erb
<section id="product-models">
  <h1>Product models</h1>
  <%= link_to "Register Product model", new_product_model_path, class: "nav-item" %>
  <% if @product_models.any? %>
    <% @product_models.each do |pm| %>
    <div class="product-card">
      <h2><%= pm.name %></h2>
      <h3><%= pm.supplier.brand_name %></h3>
      <p><%= pm.sku %></p>
    </div>
    <% end %>
  <% else %>
    <p>There are no registered Product Models.</p>
  <% end %>
</section>

app/views/product_models/new.html.erb
<div>
  <h1>New Product model</h1>
  <%= render 'form', {product_model: @product_model, suppliers: @suppliers} %>
</div>

app/views/product_models/show.html.erb
<div>
  <div>
    <h1><%= @product_model.name %></h1>
  </div>
  <div>
    <p>Supplier: <%= @product_model.supplier.brand_name%></p>
    <p>Sku: <%= @product_model.sku %></p>
    <p>Dimensions: <%= 
    "#{@product_model.width}cm x
    #{@product_model.height}cm x
    #{@product_model.depth}cm" 
    %></p>
    <p>Weight: <%= @product_model.weight %>g</p>
  </div>
</div>