config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "home#index"
  resources :warehouses, only: [:show, :new, :create, :edit, :update, :destroy]
  resources :suppliers, only: [:index, :show, :new, :create, :edit, :update]
  resources :product_models, only: [:index, :new, :create, :show]
  resources :orders, only: [:new, :create, :show, :index, :edit, :update] do
    get "search", on: :collection
    post "delivered", on: :member
    post "canceled", on: :member
    resources :order_items, only: [:new, :create]
  end

  namespace :api do
    namespace :v1 do
      resources :warehouses, only: [:show, :index, :create]
    end
  end

end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :warehouse
  belongs_to :supplier
  belongs_to :user
  has_many :order_items
  has_many :product_models, through: :order_items
  enum status: {pending: 0, delivered: 5, canceled: 9}

  validates :code, :arrival_date, presence: true
  validate :arrival_date_is_future

  before_validation :generate_code, on: :create

  private
  def generate_code
    self.code = SecureRandom.alphanumeric(10).upcase
  end

  def arrival_date_is_future
    if self.arrival_date.present? && self.arrival_date <= Date.today
      self.errors.add(:arrival_date, " deve ser futura.")
    end
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_order_and_check_user, only: [:edit, :update, :show, :delivered, :canceled]

  def edit
    @warehouses = Warehouse.all
    @suppliers = Supplier.all
  end

  def update
    if @order.update(order_params)
      return redirect_to @order, notice: "Order was successfully updated"
    end
    @warehouses = Warehouse.all
    @suppliers = Supplier.all
    render "edit"
  end

  def index
    @orders = current_user.orders
  end

  def new
    @order = Order.new
    @warehouses = Warehouse.all
    @suppliers = Supplier.all
  end

  def create
    @order = Order.new(order_params)
    @order.user_id = current_user.id
    if @order.save
      return redirect_to @order, notice: "Order was successfully issued!"
    end
    @warehouses = Warehouse.all
    @suppliers = Supplier.all
    flash.now[:notice] = "Order could not be issued"
    render "new"
  end

  def show; end

  def search
    @code = params[:query]
    @orders = Order.where("code LIKE?", "%#{@code}%")
  end

  def delivered
    @order.delivered!
    @order.order_items.each do |item|
      item.quantity.times do
        StockProduct.create(order: @order, product_model: item.product_model, warehouse: @order.warehouse)
      end
    end
    redirect_to @order
  end

  def canceled
    @order.canceled!
    redirect_to @order
  end

  private
  def set_order_and_check_user
    @order = Order.find(params[:id])
    if @order.user != current_user
      return redirect_to root_path, alert: "You don't have access to that order"
    end
  end

  def order_params
    params.require(:order).permit(
      :warehouse_id,
      :supplier_id,
      :arrival_date
    )
  end
end

app/views/orders/_form.html.erb
<div>
  <h1>Issue order</h1>
  <%= form_with model: @order do |f| %>
    <div>
      <%= f.label :warehouse_id, "Destination warehouse" %>
      <%= f.collection_select :warehouse_id, @warehouses, :id, :full_description %>
    </div>
    <div>
      <%= f.label :supplier_id %>
      <%= f.collection_select :supplier_id, @suppliers, :id, :corporate_name %>
    </div>
    <div>
      <%= f.label :arrival_date %>
      <%= f.date_field :arrival_date %>
    </div>
    
    <% if controller.action_name == "edit" %>
      <%= f.submit "Update" %>
    <% else %>
      <%= f.submit "Order" %>
    <% end %>
  <% end %>
</div>

app/views/orders/_order.html.erb
<div>
  <h2>Order <%= order.code %></h2>
  <h4>Issued by: <%= order.user.description %></h4>
  <p>Destination warehouse: <%= order.warehouse.full_description %></p>
  <p>Supplier: <%= order.supplier.corporate_name %></p>
  <p>Predicted arrival date: <%= order.arrival_date %></p>
  <p>Order status: <%= order.status %></p>
</div>

app/views/orders/edit.html.erb
<%= render 'form' %>

app/views/orders/index.html.erb
<div>
  
  <% if @orders.empty? %>
    <p>There are no orders issued yet.</p>
  <% else %>
    <% @orders.each do |order| %>
      <div id=<%= order.code%>>
        <%= render order %>
        <%= link_to 'View details', order_path(order.id) %>
        <hr>
      </div>
    <% end %>
  <% end %>
  
</div>

app/views/orders/new.html.erb
<div>
  <%= render "form" %>
</div>

app/views/orders/search.html.erb
<div>
  <h2>Search results for: <%= @code %></h2>

  <% if @orders.empty? %>
    <p>No orders were found.</p>
  <% else %>
    <p><%= @orders.length == 1 ? "1 order was found:" : "#{@orders.length} orders were found." %></p>
    <% @orders.each do |order| %>
      <p><strong>Code: </strong><%= order.code %></p>
      <p><strong>Destination warehouse: </strong><%= order.warehouse.name %></p>
      <p><strong>Supplier: </strong><%= order.supplier.corporate_name %></p>
      <p><strong>Estimated arrival date: </strong><%= order.arrival_date %></p>
    <% end %>
  <% end %>

</div>

app/views/orders/show.html.erb
<div>
  <h1>Order Details</h1>
  <hr>
  <%= render @order %>
  <%= link_to 'Edit', edit_order_path(@order.id) %>
  
  <div>
    <h2>Order items</h2>
    <%= link_to 'Add item', new_order_order_item_path(@order.id) %>
    <div>
      <% @order.order_items.each do |order_item| %>
        <p><%= "#{order_item.quantity} x #{order_item.product_model.name}" %></p>
      <% end %>
    </div>
  </div>


  <% if @order.pending? %>
    <%= button_to 'Set as delivered', delivered_order_path(@order.id) %>
    <%= button_to 'Set as canceled', canceled_order_path(@order.id) %>
  <% end %>
  
</div>