config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "home#index"
  resources :warehouses, only: [:show, :new, :create, :edit, :update, :destroy]
  resources :suppliers, only: [:index, :show, :new, :create, :edit, :update]
  resources :product_models, only: [:index, :new, :create, :show]
  resources :orders, only: [:new, :create, :show, :index, :edit, :update] do
    get "search", on: :collection
    post "delivered", on: :member
    post "canceled", on: :member
    resources :order_items, only: [:new, :create]
  end

  namespace :api do
    namespace :v1 do
      resources :warehouses, only: [:show, :index, :create]
    end
  end

end

app/models/supplier.rb
class Supplier < ApplicationRecord
  has_many :product_models

  validates :corporate_name, :brand_name, :registration_number,
  :adress, :city, :state, :email, presence: true

  validates :email, format: {with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i, on: :create}
  validates :state, length: {is:2}
  validates :registration_number, uniqueness: true
end

app/controllers/suppliers_controller.rb
class SuppliersController < ApplicationController
    before_action :get_supplier_by_id, only: [:show, :edit, :update]

    def index
      @suppliers = Supplier.all
    end

    def show; end

    def new
      @supplier = Supplier.new
    end

    def create
      @supplier = Supplier.new(supplier_params)
      if @supplier.save
        return redirect_to supplier_path(@supplier.id), notice: "Supplier successfully registered!"
      end
      flash.now[:notice] = "Could not register supplier."
      render "new"
    end

    def edit; end

    def update
      if @supplier.update(supplier_params)
        return redirect_to supplier_path(@supplier.id), notice: "Supplier edited successfully!"
      end
      flash.now[:notice] = "Could not edit supplier."
      render "edit"
    end

    private
    def supplier_params
      params.require(:supplier).permit(
        :corporate_name,
        :brand_name,
        :registration_number,
        :adress,
        :city,
        :state,
        :email
      )
    end

    def get_supplier_by_id
      @supplier = Supplier.find(params[:id])
    end
end

app/views/suppliers/_form.html.erb
<div>

  <% if supplier.errors.any? %>
    <p>Verify the errors bellow:</p>
    <ul>
      <% supplier.errors.full_messages.each do |err| %>
        <li><%= err %></li>
      <% end %>
    </ul>
  <% end %>

  <%= form_with model: supplier do |f| %>
    <div>
      <%= f.label :corporate_name%>
      <%= f.text_field :corporate_name %>
    </div>
    <div>
      <%= f.label :brand_name%>
      <%= f.text_field :brand_name %>
    </div>
    <div>
      <%= f.label :registration_number%>
      <%= f.text_field :registration_number %>
    </div>
    <div>
      <%= f.label :adress%>
      <%= f.text_field :adress %>
    </div>
    <div>
      <%= f.label :city%>
      <%= f.text_field :city %>
    </div>
    <div>
      <%= f.label :state%>
      <%= f.text_field :state %>
    </div>
    <div>
      <%= f.label :email%>
      <%= f.text_field :email %>
    </div>
    <div>
      <%= f.submit "Save"%>
    </div>
  <% end %>
</div>

app/views/suppliers/edit.html.erb
<div>
  <%= render 'form', supplier: @supplier %>
</div>

app/views/suppliers/index.html.erb
<section id="suppliers">
  <h1>SUPPLIERS</h1>

  <div>
    <%= link_to 'Register supplier', new_supplier_path %>
  </div>
  <div>
    <% if @suppliers.any?%>
      <table>
        <tr>
          <th>Corporate</th>
          <th>Brand</th>
          <th>State</th>    
        </tr>
        <% @suppliers.each do |supplier| %>
          <tr>
            <td><%= link_to supplier.corporate_name, supplier %></td>
            <td><%=supplier.brand_name %></td>
            <td><%=supplier.state %></td>
          </tr>
        <% end %>
      </table>
    <% else %>
      <p>There are no registered Suppliers</p>
    <% end %>
  </div>
  <div>
    <%= button_to "Back", root_path, method: :get %>
  </div>

</section>

app/views/suppliers/new.html.erb
<div>
  <%= render 'form', supplier: @supplier %>
</div>

app/views/suppliers/show.html.erb
<div>
  <div>
    <h1><%= @supplier.corporate_name %></h1>
    <h3><%= @supplier.brand_name %></h3>
  </div>
  <div>
    <p>Registration number: <%= @supplier.registration_number %></p>
    <p>Adress: <%= @supplier.adress %></p>
    <p>City: <%= @supplier.city %></p>
    <p>State: <%= @supplier.state %></p>
    <p>Email: <%= @supplier.email %></p>
  </div>
  <div>
    <%= button_to "Edit", edit_supplier_path, method: :get %>
    <%= button_to "Back", suppliers_path, method: :get %>
  </div>
</div>