config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "home#index"
  resources :warehouses, only: [:show, :new, :create, :edit, :update, :destroy]
  resources :suppliers, only: [:index, :show, :new, :create, :edit, :update]
  resources :product_models, only: [:index, :new, :create, :show]
  resources :orders, only: [:new, :create, :show, :index, :edit, :update] do
    get "search", on: :collection
    post "delivered", on: :member
    post "canceled", on: :member
    resources :order_items, only: [:new, :create]
  end

  namespace :api do
    namespace :v1 do
      resources :warehouses, only: [:show, :index, :create]
    end
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WarehouseApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application" %>
  </head>

  <body>
    <header>
      <div class="center">
        <%= link_to root_path do %>
          <h1>Warehouses & Inventory</h1>
        <% end %>
      </div>
      <nav class="center">
        <%= link_to 'Suppliers', suppliers_path, class: "nav-item" %>
        <%= link_to 'Warehouses', root_path, class: "nav-item" %>
        <%= link_to 'Product models', product_models_path, class: "nav-item" %>
        <%= link_to 'Issue order', new_order_path, class: "nav-item" %>

        <% if user_signed_in? %> 
          <%= link_to 'My orders', orders_path %>
          <%= button_to 'Logout', destroy_user_session_path, method: :delete, class: "nav-item" %>
          <%= "Signed in as: #{current_user.description}" %>
          <%= form_with url: search_orders_path, method: :get do |f| %>
          <div>
            <%= f.label :query, "Search order" %>
            <%= f.text_field :query %>
          </div>
          <%= f.submit "Search" %>
        <% end %>
        <% else %>
          <%= link_to 'Login', new_user_session_path, class: "nav-item" %>
        <% end %>

      </nav>
    </header>
    <hr>
    <p class="center"><%= notice %></p>
    <p class="center"><%= alert %></p>
    <main id="main">
      <div>
        <%= yield %>
      </div>
    </main>
  </body>
</html>